index.js
lib/util.js
test/util-specs.js

@sebv @jlipps Please take a look at this.  This is for the xcode version changes.  I moved the the `notNullOrUndefined` functions here and renamed them to `hasContent` and `hasValue`.

Added hasContent/Value

---

lib/util.js
package.json

will need to update package.json file in appium and other libs

add underscore and update version

---

lib/util.js

This code just copied from future.js in appium, so that we don't have to copy code between different future.js files in different appium modules

Nodeify module

---

lib/util.js
test/util-specs.js

from https://github.com/appium/appium/commit/839b9a893e3fb1958d9687b3f5401d7f127f4d75
because I am replacing xcode.js

add util.escapeSpace()

---

lib/util.js
test/util-specs.js

This function is used in appium, in test/helpers/env.js
Moving it into appium-support so we can use it in the main project (for execute async)

add localIp function

---

index.js
test/index-specs.js
test/system-specs.js
test/tempdir-specs.js
test/util-specs.js

Fix the exports from `index`, and test them.

Add index tests, and use index in other tests

---

lib/fs.js
test/fs-specs.js

Add `stat` to the `fs` methods we promisify.
Also clean up some `eventually`s in the tests.

Add stat to promisified fs object

---

index.js
lib/mkdirp.js
lib/util.js
package.json

adds mkdirp multiresolve

---

lib/plist.js
package.json
test/plist-specs.js

Mixed up the import. Added a test so that it is caught.

Fix wrong import of fs

---

lib/fs.js
package.json
test/fs-specs.js

Adding lstat and mv to fs

---

lib/mkdirp.js

Async `mkdirp` wasn't working. Manually promisify.

Fix mkdirp

---

README.md
lib/system.js
package.json
test/system-specs.js

appium-doctor todo https://github.com/appium/appium-doctor/issues/3
@imurchie

Moved macOsxVersion to appium-support + bump to 2.0.4

---

lib/plist.js

Plist logging was much too verbose. Clean up, and put behind a flag.

Clean up logging

---

lib/util.js
test/util-specs.js

We use this in ios and xcuitest, and probably elsewhere in _ad hoc_ ways. It's simply, but does not need to be repeated.

Add unwrapElement method to util

---

lib/system.js

Fixes https://github.com/appium/appium/issues/9415

Add mac 10.13 to list of possible mac versions

---

.gitignore
.npmrc

Stop making package-lock.json file

---

package.json
test/image-util-specs.js
test/index-specs.js
test/logger/logger-force-specs.js
test/logger/logger-normal-specs.js
test/logger/logger-test-specs.js
test/plist-specs.js
test/process-specs.js
test/system-specs.js
test/tempdir-specs.js
test/util-specs.js
test/zip-specs.js

Add a gulp task for fixing eslint. And fix the arrow functions in mocha.
appium/appium#10016

Get rid of arrow functions in mocha aparatus

---

lib/net.js

Remove unused argument from uploadFileToHttp method

---

lib/image-util.js
test/image-util-specs.js

I think this might be more handy for the clients

Return full size of the matched area

---

.travis.yml
test/image-util-specs.js

@mykola-mokhnach Here is the basics of getting it in Travis. It doesn't work. Feel free to experiment on getting it to work.

Update travis config to install opencv

---

.gitignore
lib/net.js

Fix importing and using of `fs` module.
Fixes https://github.com/appium/appium/issues/10630

Fix uploading of files

---

lib/util.js
test/util-specs.js

This helper will be extremely useful for security purposes

Add an utility method for subpath verification

---

.travis.yml
lib/fs.js
test/fs-specs.js

Addresses https://github.com/appium/appium-espresso-driver/pull/256#issuecomment-431646541

Add source verification for copyFile method

---

lib/util.js
package.json
test/util-specs.js

Such method might be useful in multiple modules

Add utility method for versions comparison

---

lib/image-util.js

Addresses https://github.com/appium/appium/issues/12849

Make the module compatible to opencv4nodejs 5

---

lib/util.js
test/util-specs.js

It looks like there is a memory leak while reassigning function arguments.

Tune safe json parsing

---

lib/fs.js
test/fs-specs.js

This fixes asynchronous promises execution for https://github.com/appium/appium-support/pull/135

fix: Fix promises handling in the file system walker callback

---

lib/mjpeg.js

Hopefully addresses https://github.com/appium/appium/issues/13560

fix: Return proper result if MJPEG server cannot parse the incoming data

---

lib/image-util.js
test/image-util-e2e-specs.js

https://github.com/appium/appium/issues/13883
Returns similarity score as the result of `getImageOccurrence`

feat: returns similarity  score by getImageOccurrence

---

lib/net.js

I observe the code for files download could be reused in multiple modules, so it makes sense to move it here

feat: Add helper for files download

---

lib/net.js
test/net-e2e-specs.js

Related to https://github.com/appium/appium/issues/14534

chore: Validate Content-Length response header for file downloads

---

lib/fs.js
lib/net.js

It was just a coincidence that the previous implementation worked :)

fix: Get headers from the response object

---

lib/net.js
test/image-util-e2e-specs.js

https://discuss.appium.io/t/need-support-uploading-of-screen-recording-to-opened-s3/33254

feat: Add a possibility to perform non-multipart file uploads

---

lib/image-util.js

Related to https://discuss.appium.io/t/appium-opencv-images-differing-only-in-color-accept-as-equal/33567
@khaong Could you please help to review the PR?

feat: Make it possible to customize the method name for OpenCV-based template matching

---

lib/mjpeg.js
package.json
test/mjpeg-e2e-specs.js

Related to https://github.com/appium/appium/issues/15320

chore: Move mjpeg-server import to dev dependencies

---

lib/zip.js

Since standalone unzip does not exist in Windows we could use PowerShell features to replace it: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-7.1

feat: Add a possibility to use PowerShell to unzip files in Windows

---

lib/net.js

Related to https://github.com/appium/java-client/pull/1591

fix: Only set Content-Length header for non-multipart uploads
