appium/appium-support

- lib/fs.js
- package.json
I messed up the import for `md5` when upgrading, which only seemed to cause problems in Travis. This fixes that and bumps version.
> Fix md5 import

- lib/plist.js
- test/plist-specs.js
In some cases, we don't want an error thrown if a plist file doesn't exist.
Please review @jlipps
> Added mustExist flag to parsePlistFile

- lib/plist.js
On error we don't have any indication of what file is failing us.
> Make sure plist name gets into log

- lib/util.js
- test/util-specs.js
Lodash stopped having a `pluck` method.
Also, fix the test for `util.localIp` so that it actually tests something, rather than just mocking the method under test. :(
> Use map instead of pluck

- lib/fs.js
node-adb-client makes use of `fs.read` to read specific chunk sizes from a file
> add fs.read function to fs promisified functions

- lib/tempdir.js
Avoids race condition where code run later expects there to be a tmp directory prepared.
> Await on the returned Promise from mkdir

- lib/system.js
- test/system-specs.js
Add latest macOS release to list of acceptable versions. While this will not necessarily mean that macOS 10.12 is supported, it at least means that it will not be stopped by simple checks for validity.
Addresses https://github.com/appium/appium/issues/6609
> Allow macOS 10.12 to be found

- lib/system.js
- test/system-specs.js
It seems that on macOS the output sometimes has spaces and a newline at the end (see output in https://github.com/appium/appium/issues/6609#issuecomment-252304758). Use `trim()` to get rid of that.
> Add trim to mac version check

- .travis.yml
- lib/tempdir.js
Node 7 deprecated `tmpDir`. `tmpdir` is available in all the versions we support (https://nodejs.org/api/os.html#os_os_tmpdir).
> Use os.tmpdir instead of tmpDir

- README.md
- index.js
- lib/logging.js
- package.json
- test/logger/helpers.js
- test/logger/logger-force-specs.js
- test/logger/logger-normal-specs.js
- test/logger/logger-test-specs.js
Move logger into the support package, for use from other packages. @jlipps
> Move logger from appium-base-driver into support

- index.js
- lib/process.js
- package.json
- test/process-specs.js
In a few places we check for a process, and kill it. Consolidate it so that it is tested properly and available to whomever needs it.
> Add helpers for process management

- lib/logging.js
Reduce memory usage by limiting the size of internal log buffer.
> Decrease maximum log records count to stabilise memory usage

- .gitignore
- lib/zip.js
- test/zip-specs.js
My editor deletes trailing spaces, so there is some chaff in there. The essential part is `lib/zip.js`, lines 90-92. If the directory is not there, fail.
Otherwise the `appium-xcuitest-driver` [build fails catastrophically](https://travis-ci.org/appium/appium-xcuitest-driver/jobs/226870050#L5961-L5982) on [this test](https://github.com/appium/appium-xcuitest-driver/blob/master/test/functional/basic/file-movement-e2e-specs.js#L59-L61).
> Fail zipping directory to which we have no access

- lib/logging.js
- test/logger/logger-normal-specs.js
This will be needed to implement more advanced logging mechanism for parallel drivers. The idea is to create a single logger instance per driver instance and, as a log prefix, provide a special function, which adds session id if it exists for the current driver instance.
P. S. The whole idea might suck, so it would be pretty ok if this PR is closed :)
> Add a possibility to pass dynamic prefix generator to a logger instance

- lib/logging.js
This should address memory leak issue caused by the fact that original strings are kept in memory after _.truncate operation is done on them. And since logs have an internal buffer of size 3000, where all logged strings are stored by by default, this might cause serious leaks in case some really big strings are being truncated and then passed to logs.
> Workaround memory leak issue caused by truncated strings

- test/fs-specs.js
Some general cleanup. Main change is to use small size for blocks to write in md5 test. On 10.13 the blocksize is huge and it slows the test down (or causes a memory error). 4096 bytes is ample and the tests remain fast.
> Fix tests on Mac 10.13

- lib/net.js
It looks like the parsed protocol name also includes a colon at the end
> Fix protocol name comparsion

- lib/util.js
- package.json
- test/util-specs.js
In order to not have a mix of versions of `bluebird`, this package needs to be updated. Unfortunately `Promise.cancel` has been changed significantly (see http://bluebirdjs.com/docs/api/cancellation.html#cancellation). It used to abort the promise, where now it just makes it so `resolve` or `reject` are not called.
This PR just overrides the `cancel` function to do essentially what it did before.
> Update bluebird and make cancellable delay work

- lib/image-util.js
- test/image-util-specs.js
my belief is that the primary use of this feature is to find things that exist on the screen, not to find the most likely place for them to exist (even when they don't).
to get the old behavior, just set threshold to 0
> reject image template matches below a threshold of default 0.5

- lib/image-util.js
- lib/mjpeg.js
- test/image-util-e2e-specs.js
was finding that i was having to do lots of bluebird messiness just to use jimp in a few different places. this PR puts all that messiness in one place.
> add some jimp helper functionality

- lib/mjpeg.js
- package.json
Rather than insisting that everyone install `mjpeg-consumer`, which has a dependency on `buffertools` which gets built natively, lazily load the package when it is needed, insisting that users who want this feature install the package themselves.
Without this it becomes impossible to do things like bundle Appium and run on a different system, upgrade Node without reinstalling altogether, etc.
> Only load mjpeg-consumer package at runtime

- lib/system.js
- test/system-specs.js
Addresses https://github.com/appium/appium/issues/11422
I would assume such verification should not be located in the library, but in the client code instead (appium-doctor in such case if it is necessary at all).
> Do not check the list of supported versions

- index.js
- lib/util.js
- test/util-specs.js
* `unwrapElement` should work for both [W3C elements](https://www.w3.org/TR/webdriver1/#elements) (`{"element-6066-11e4-a52e-4f735466cecf": "<ELEMENT-UUID>"}`) and JSONWP elements (`{"ELEMENT": "<ELEMENT-UUID>"}`)
* It prioritizes the W3C uuid when both are provided:
* e.g.)
```
{
"ELEMENT": 1,
"element-6066-11e4-a52e-4f735466cecf": 2 
}
```
will be unwrapped as 2.
> Unwrap w3c elements

- lib/fs.js
The `fs` object here does not contain the necessary constants, so they all are equal to `undefined`. The constants should be imported from the system module instead or copied to our wrapper explicitly.
> Fix the constant in hasAccess method

- .travis.yml
- package.json
I do not have the time right now to make the fully generalized solution proposed in #105. However, if `opencv4nodejs` is already globally installed, it can be used by linking into this package. So check and link if it is there, after the install.
> Link global opencv4nodejs to give access

- lib/fs.js
So we do not need to import Node's `fs` just to do things with our `fs`.
> Add fs constants to our fs object

- lib/tempdir.js
- test/tempdir-specs.js
I've tested below patterns in [ruby_lib_core test suite](https://github.com/appium/ruby_lib_core/tree/master/test/functional) adding logs in `tempDir` module:
- Run a single device test
- Android
- UIA2
- Espresso
- iOS
- XCUITest
- Run tests in parallel in single Appium server instance
- Android x 3 emulators
- UIA2
- Espresso
- iOS x 2 simulators
- XCUITest
- Android x 3, iOS x 2
The ruby_lib_core include screen recording, pull/push apks like https://github.com/appium/appium-android-driver/pull/538
Then, I ensured Appium log had no `/var/folders/xxxx`. They called `--tmp` arg.
----
Working for https://github.com/appium/appium/issues/12527
Appium can get `--tmp` as http://appium.io/docs/en/writing-running-appium/server-args/#server-flags. In some method, the flag is respected.
But …
> add tmpDir arg for tempdir to respect server tmpdir flag

- lib/image-util.js
I found a typo which is used in _find element by image_ like below:
```
if (err.message.match(/Cannot find any occurrences/)) {
return false;
}
```
> fix typo for occurrences message

- lib/fs.js
So that we don't need to import both Node's `fs` and ours, to use them.
> Add createReadStream and createWriteStream to fs

- .travis.yml
- lib/zip.js
- test/zip-e2e-specs.js
This method will be needed for adb, because Google has removed apk file management primitives from aapt2
> Add a helper method to compress file hierarchies based on glob pattern

- lib/util.js
- test/util-specs.js
Attempt to reduce the footprint of a package we use all over the place. Recently `shell-quote` was updated four times in succession, which means Greenkeeper ran four branches through CI for every package that imports it. If the functionality is verified here, then we can safely use it throughout.
> feat: add function to abstract away shell-quote

- lib/logging.js
- lib/util.js
- test/util-specs.js
The system logger keeps the internal records buffer, so when we log some big string or even part of it (by using, for example, substring or split calls) then the whole string is kept in memory until the log buffer is large enough to free up the outdated items. In this PR we make sure that log items are always being unleaked, which means we never keep a pointer to the large string, but rather a separate string object in the log buffer. 
I was also thinking about limiting the maximum length of a single line we can put into the log, to, for example, 1MB. Currently the maximum size of the log buffer is set to 3000 records, which is 3 GB in total if all records would have their maximum sizes.
> fix: Make sure all logged strings are always being unleaked

- lib/util.js
- test/util-specs.js
Add a general-purpose function to serialize objects while respecting Buffers. This is currently used in `appium-remote-debugger`, and it has a place in `appium-ios-device`
> feat: add function to stringify objects with Buffers

- lib/fs.js
- test/fs-specs.js
Fixed fs.walkDir to wait until callback completion of last file.
Fix: https://github.com/appium/appium/issues/13515
Note: fix pull request author of https://github.com/appium/appium-support/pull/138
> Issue  #13515

- .travis.yml
Our caching no longer works, and so the build fails. This takes a little longer, but at least runs things.
> build: do not cache npm dir

- .travis.yml
- gulpfile.js
- lib/node.js
- test/fs-specs.js
- test/image-util-e2e-specs.js
Re-enable global `node_modules` caching in Travis. Also remove the masking of the install process for `opencv4nodejs` as, in the event of an error in install/build, it makes the problem unclear.
> build: fix node caching in travis

- lib/util.js
We use the `bigint` option for `fs.stat`, but below Node 10.5.0 the options are interpreted as the callback, which fails. Until we no longer support Node 10, this needs to be properly handled.
> fix: make things run on Node < 10.5

- .eslintrc
- index.js
- lib/timing.js
- test/fs-specs.js
- test/timing-specs.js
We have a number of different mechanisms for getting the duration of operations. This is a first pass at making an extensible API for our use. Once the Performance API is out of super-experimental in Node, this could encapsulate that too, without needing application code to be messed with.
> feat: add timing API

- lib/fs.js
- package.json
- test/fs-specs.js
I was working on an issue with the removal of files, and there was no visibility into what this function was doing. So log the final output when things are done.
> refactor: more visibility into walking the directories

- lib/mkdirp.js
Node 10.12 introduced the `recursive` option to `fs.mkdir`(https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback).
> chore: add todo to get rid of mkdirp dep

- lib/fs.js
- lib/util.js
- package.json
- test/util-specs.js
Add export of https://github.com/blakeembrey/pluralize through the `util` module.
> feat: export pluralize functionality

- lib/node.js
Node 12 recently broke how were were accommodating global requires. This adds a step to try where the package ought to be as an absolute path.
This will fix the build, too.
> fix: when requiring globally, try direct path first

- lib/util.js
- lib/zip.js
- package.json
- test/util-e2e-specs.js
- test/zip-e2e-specs.js
Streamed base64 encoding will help to save memory, since sometimes the amount of data passed to `toInMemoryZip` helper is super large. Also having some precautions like maxSize wouldn't hurt us in any case
> feat: Perform fine-tuning of toInMemoryZip helper

- lib/util.js
- package.json
I can observe that different libs for uuids generation are being imported by different Appium modules (for example the outdated uuid-js). They must be unified and be accessible from appium-support instead.
> feat: Add primitives for uuid generation

- .dependabot/config.yml
`extract-zip@2.0.0` removed support for Node < 10.12 (https://github.com/maxogden/extract-zip/releases/tag/v2.0.0). Since Appium supports 10 (until the fall, assuming Node keeps its normal release cadence during this time) we cannot update.
> chore: dependabot do not update extract-zip

- lib/net.js
This skips logging the contents of the screen recording video to the debug log.
The video is massive and outputting it to the debug log in a integer array format both slows down (or crashes) the process and limits the usability of the logs.
> fix: Exclude the recorded video contents from the log

- lib/util.js
- test/util-e2e-specs.js
There could be cases where a process has been forcefully terminated without a chance to clean up pending locks: https://github.com/npm/lockfile/issues/26
> feat: Add an option to recover a "broken" file lock

- lib/mjpeg.js
Related to https://github.com/appium/appium/issues/15209
> fix: Make sure we don't get an outdated screenshot if there was an error in MJPEG consumer

- lib/image-util.js
Closes https://github.com/appium/appium-support/issues/220
When `matchTemplateAsync` fails, `getImageOccurrence` raises an error message which is `Cannot find any occurrences of the partial image in the full image`, meanwhile `getImagesSimilarity` returns no message. As a client, it only gets 'internal server error' with `undefined` error message.
It seems `e.message` by opencv4nodejs is usually `undefined`.
In addition to it, server-side message is like the below.
```
[debug] Support Loading local package 'opencv4nodejs'
[debug] [W3C (f7b505ad)] Encountered internal error running command: undefined
HTTP] <-- POST /wd/hub/session/f7b505ad-2e91-417b-86ea-e78ea94d1609/appium/compare_images 500 142 ms - 527
[HTTP]
```
So, i'd like to add more messages about no matched images there.
(Rarely …
> chore: try/catch in matchTemplateAsync for error message

- lib/zip.js
- test/zip-e2e-specs.js
For performance reasons with larger files (or perhaps just archives containing thousands of files), system `unzip` provides much better perf (~3x) than the native implementation.
Instead of simply preferring it over the native one, given option `useSystemUnzip: true` to `extractAllTo()`, we will now:
1. look in the `PATH` for `unzip` (cache the location)
2. if it's there, use it instead. if not, fall back to JS
3. if it fails for any reason, fall back to JS
If `useSystemUnzip` is falsy, we will use the JS implementation; the user need not change any code.
This strategy provides robust, opt-in behavior for better performance where needed.
The ultimate aim is for `appium-base-driver`/`@appium/base-driver` to leverage this behavior.
**This will need  to be backported (forward-ported?) to …
> feat(zip): extractAllTo(): default to system unzip if present

- lib/net.js
The previous default timeout value is definitely too low, especially for uploads. While setting it for the first time I thought this is a READ timeout but it turns out this is a global timeout for any axios request
> chore: Increase the default timeout for upload/download

- lib/image-util.js
The original repository is not maintained, so one might get a hard time now if try to compile and link an older OpenCV version to it. The fork at https://www.npmjs.com/package/@u4/opencv4nodejs updates basic deps, so now it is possible to use the most recent OpenCV releases.
> refactor: Try to load opencv4nodejs from the working fork by default
